version: '3'
services:
  pylanthia:
    container_name: pylanthia_app
    build: .
    volumes:
      - .:/app:delegated
    entrypoint: "/bin/bash -c"
    command: "/app/entrypoint.sh"
  debug:
    container_name: pylanthia_debug
    build: .
    ports:
      - "4901:4901"
    volumes:
      - .:/app:delegated
    entrypoint: "/bin/bash"
